### ISSUE TITLE
Save the selection of "Limit Row Number"

### ISSUE THREAD

**Issue by chengzhou2046** [ckyycc/ngx-hana-nameserver-history-viewer#2]
I need to select "Limit Row Number" every time after reloading the page because the default 100K is not enough sometimes. It could be better to save it in cookie or somewhere.

**Comment by ckyycc** [comment]
> I need to select "Limit Row Number" every time after reloading the page because the default 100K is not enough sometimes. It could be better to save it in cookie or somewhere.

Thanks a lot for the suggestion. Now the "Limit Row Number" and "Measure" will be saved to local storage in the demo. 

However, this feature is not relative to the library itself. let me close this issue with "enhancement" and "others".
