### ISSUE TITLE
Unit of Memory Related Rows

### ISSUE THREAD

**Issue by chengzhou2046** [ckyycc/ngx-hana-nameserver-history-viewer#3]
Is it possible to change the unit of memory related rows (Physical Memory Size, Database Used Memory, Memory Used and so on) from MB to GB or make it configurable? Normally we only talk about "GB" for memory size, right?

**Comment by ckyycc** [comment]
Although this is configurable in the tool, still decided not to change it from MB to GB. 
Reasons:
1. global_allocation_limit is using MB as unit.
2. hana studio and cockpit are using MB for those items.

**Comment by chengzhou2046** [comment]
> Although this is configurable in the tool, still decided not to change it from MB to GB.
> Reasons:
> 
> 1. global_allocation_limit is using MB as unit.
> 2. hana studio and cockpit are using MB for those items.

Understood. But could you format the numbers in the tooltips with commas? It's really not easy to calculate without commas...

**Comment by ckyycc** [comment]
[1.0.15](https://github.com/ckyycc/ngx-hana-nameserver-history-viewer/tree/1.0.15) is released with the feature of formatting numbers of tooltips, let me close this issue with "wontfix". Any other question/request, please feel free to let me know.
