### ISSUE TITLE
Some items show value -1

### ISSUE THREAD

**Issue by masakiobata** [ckyycc/ngx-hana-nameserver-history-viewer#6]
![itemwith-1](https://user-images.githubusercontent.com/45721116/50412368-a2e00e80-0841-11e9-8733-82d9a20140fb.png)

**Comment by ckyycc** [comment]
Is it possible to upload me the nameserver_history.trc? 
Or help me check the column dataBackupWriteSize of this file? You can do it via:
1. copy nameserver_history.trc to somewhere.
2. modify nameserver_history.trc to nameserver_history.csv
3. open nameserver_history.csv using Excel
4. check column dataBackupWriteSize, and let me know the detail of this column.

**Comment by ckyycc** [comment]
The issue was fixed with [release 1.1.2 ](https://github.com/ckyycc/ngx-hana-nameserver-history-viewer/releases/tag/1.1.2)
